market:
  enabled_symbols: ["BTC","ETH","SOL","DOGE"]
  page_size: 21
  gui_title: "&6Crypto Market"
  refresh_seconds: 15

chart:
  retention_points: 360
  sample_seconds: 60
  default_points: 24
  default_range: "h1"
  sparkline_chars: "▁▂▃▄▅▆▇█"

placeholders:
  enabled: true
  format:
    money: "#,##0.00"
    quantity: "#,##0.####"

api:
  timeout_ms: 4000
  retry: 1
  circuit_breaker:
    error_threshold: 5
    open_seconds: 30


messages:
  prefix: "&6[&eCrypto&6] &r"
  no_permission: "&cYou don't have permission."
  player_only: "&cPlayers only."
  invalid_amount: "&cInvalid amount."
  help:
    header: "&eAvailable commands:"
  usage:
    price: "&eUsage: /{label} price <symbol...>"
    trade: "&eUsage: /{label} {sub} <symbol> <amount>"
    balance: "&eUsage: /{label} balance <player>"
    transfer: "&eUsage: /{label} transfer <player> <symbol> <amount>"
    convert: "&eUsage: /{label} convert <symbol> <symbol2> <amount>"
    edit: "&eUsage: /{label} {sub} <player> <symbol> <amount>"
    giveall: "&eUsage: /{label} giveall <symbol> <amount>"
    history: "&eUsage: /{label} history [player] [limit]"
    chart: "&eUsage: /{label} chart <symbol> [points] [range]"
    api: "&eUsage: /{label} api <status|refresh>"
    api.refresh: "&eUsage: /{label} api refresh <symbol>"
  price:
    error: "&cError fetching {symbol} price: {error}"
  chart:
    hydrating: "&7Fetching price history for &e{symbol}&7... Try again in a few seconds."
  top:
    header: "&eTop {limit} investors:"
    empty: "&7No investors found."
  reload:
    ok: "&aConfiguration reloaded."
  balance:
    empty: "&eWallet of &f{player} &7: (empty)"
    header: "&eWallet of &f{player}:"
    total: "&7Total value: &a${total}"
    error: "&cError while calculating wallet: {error}"
  trade:
    buy:
      nomoney: "&cNot enough funds. Required: ${usd} | Balance: ${balance}"
      success: "&aPurchase: &f{amount} {symbol} &7(-${usd})"
      failed: "&cPurchase failed: {error}"
      simulated: "&eSimulated purchase: &f{amount} {symbol} &7(~${usd})"
    sell:
      notenough: "&cYou don't have enough {symbol}. Owned: {owned}"
      success: "&aSale: &f{amount} {symbol} &7(+${usd})"
      failed: "&cSale failed: {error}"
      simulated: "&eSimulated sale: &f{amount} {symbol} &7(~${usd})"
  transfer:
    self: "&cYou cannot transfer to yourself."
    notenough: "&cYou don't have enough {symbol}. Owned: {owned}"
    success: "&aTransfer: &f{amount} {symbol} &7→ &f{player}"
    failed: "&cTransfer failed."
  convert:
    notenough: "&cYou don't have enough {symbol}. Owned: {owned}"
    invalid_target: "&cCannot convert to {symbol}."
    success: "&aConversion: &f{from_amount} {from_symbol} &7→ &f{to_amount} {to_symbol}"
    failed: "&cConversion failed."
    error: "&cError during conversion: {error}"
  admin:
    set:
      success: "&aSet: &f{player} &7now has &f{amount} {symbol}"
    add:
      success: "&aAdded: &f{amount} {symbol} &7to &f{player}"
    remove:
      success: "&aRemoved: &f{amount} {symbol} &7from &f{player}"
      failed: "&c{player} doesn't have enough {symbol}."
  giveall:
    received: "&aAirdrop: You received &f{amount} {symbol}!"
    success: "&aAirdrop: &f{amount} {symbol} &7distributed to &f{count} &7player(s)"
  history:
    header: "&eHistory of &f{player} &7({count} recent transactions):"
    empty: "&7No transactions found."
  api:
    status: "&7API Status: {status}{status_name}"
    refresh: "&7Refreshing &e{symbol} &7..."
    refresh:
      success: "&a{symbol} &7= &a${price}"
      failed: "&cRefresh failed: {error}"
