market:
  enabled_symbols: ["BTC","ETH","SOL","DOGE"]
  page_size: 21
  gui_title: "&6Crypto Market"
  refresh_seconds: 15

chart:
  retention_points: 360
  sample_seconds: 60
  default_points: 24
  default_range: "h1"
  sparkline_chars: "▁▂▃▄▅▆▇█"

placeholders:
  enabled: true
  format:
    money: "#,##0.00"
    quantity: "#,##0.####"

api:
  timeout_ms: 4000
  retry: 1
  circuit_breaker:
    error_threshold: 5
    open_seconds: 30


messages:
  prefix: "&6[&eCrypto&6] &r"
  no_permission: "&cYou don't have permission."
  player_only: "&cPlayers only."
  invalid_amount: "&cInvalid amount."
  help:
    header: "&eAvailable commands:"
  usage:
    price: "&eUsage: /{label} price <symbol...>"
    trade: "&eUsage: /{label} {sub} <symbol> <amount>"
    balance: "&eUsage: /{label} balance <player>"
    convert: "&eUsage: /{label} convert <symbol> <symbol2> <amount> &7(placeholder)"
    edit: "&eUsage: /{label} {sub} <player> <symbol> <amount> &7(placeholder)"
    giveall: "&eUsage: /{label} giveall <symbol> <amount> &7(placeholder)"
    history: "&eUsage: /{label} history [player] &7(placeholder)"
    chart: "&eUsage: /{label} chart <symbol> [points] [range]"
    api: "&eUsage: /{label} api <status|refresh> &7(placeholder)"
  price:
    error: "&cError fetching {symbol} price: {error}"
  chart:
    hydrating: "&7Fetching price history for &e{symbol}&7... Try again in a few seconds."
  top:
    placeholder: "&eTop 5 investors: &7(placeholder)"
  reload:
    ok: "&aConfiguration reloaded."
  balance:
    empty: "&eWallet of &f{player} &7: (empty)"
    header: "&eWallet of &f{player}:"
    total: "&7Total value: &a${total}"
    error: "&cError while calculating wallet: {error}"
  trade:
    buy:
      nomoney: "&cNot enough funds. Required: ${usd} | Balance: ${balance}"
      success: "&aPurchase: &f{amount} {symbol} &7(-${usd})"
      failed: "&cPurchase failed: {error}"
      simulated: "&eSimulated purchase: &f{amount} {symbol} &7(~${usd})"
    sell:
      notenough: "&cYou don't have enough {symbol}. Owned: {owned}"
      success: "&aSale: &f{amount} {symbol} &7(+${usd})"
      failed: "&cSale failed: {error}"
      simulated: "&eSimulated sale: &f{amount} {symbol} &7(~${usd})"
